# Generated by Django 3.0.8 on 2020-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0003_pemilih'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='pil1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='pil2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='pil3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='pil4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='pil5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='pil6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='batas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
