# Generated by Django 3.0.8 on 2020-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0004_auto_20200906_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='status',
            field=models.CharField(choices=[('BELUM', 'belum'), ('SUDAH', 'sudah')], default='BELUM', max_length=5),
        ),
    ]
