# Generated by Django 3.0.8 on 2020-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0005_pemilih_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilih',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
