# Generated by Django 3.0.8 on 2020-09-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0008_grupkandidat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupkandidat',
            name='user',
        ),
    ]
