# Generated by Django 3.0.8 on 2020-09-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0009_remove_grupkandidat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidat',
            name='voting',
        ),
    ]
