# Generated by Django 3.0.8 on 2020-09-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0010_remove_kandidat_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='pilihanumum',
            field=models.BooleanField(default=False),
        ),
    ]
